services:
  - type: web
    name: aternos-server
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libatk1.0-0 libxss1 libappindicator1 libindicator7 libasound2 fonts-liberation libappindicator3-1 xdg-utils libu2f-udev
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: "python server.py"
    envVars:
      - key: EMAIL
        value: richer.moni777@gmail.com
      - key: PASSWORD
        value: 543regeon
